#Make debian minimal rootfs.

add_var "declare -gx" "dir" "${default_dir:-/mnt/mnt}"
add_var "declare -gx" "distr" "astra"
add_var "declare -gx" "LANG_SYSTEM" "en_US.UTF-8"
add_var "declare -gx" "hostname" "$distr"
add_var "declare -gx" "user_name" "$user_name"
add_var "declare -gx" "user_shell" "$user_shell"
add_var "declare -gx" "passwd" "$passwd_default"
add_var "declare -gx" "bootloader" "0"
add_var "declare -gx" "kernel" "0"
add_var "declare -gx" "add_soft" "0"
add_var "declare -gx" "arch" "amd64"
add_var "declare -gx" "ASTRA_MODE" "1"
add_var "declare -gx" "deb_add_option" "--no-check-gpg --exclude=usr-is-merged --components=main,contrib,non-free"
add_var "declare -gx" "version_astra" "orel"
add_var "declare -gx" "version_debian" "stable"
add_var "declare -gA" "debian_repos"
add_var "declare -ga" "debian_repos_order"
add_var "declare -gx" "debian_repos[main]" "deb $astra_mirror $version_debian main non-free contrib"
add_var "declare -gx" "debian_repos_order[0]" "main"
add_var "declare -gx" "repos" "0"
add_var "declare -gx" "debian_add_i386" "1"
add_var "declare -gx" "preinstall" "locales"
add_var "declare -gx" "postinstall" ""
