#Make debian minimal rootfs.

add_var "declare -gx" "dir" "${default_dir:-/mnt/mnt}"
add_var "declare -gx" "distr" "debian"
add_var "declare -gx" "hostname" "debian"
add_var "declare -gx" "user_name" "user"
add_var "declare -gx" "user_shell" "/bin/bash"
add_var "declare -gx" "passwd" "pass"
add_var "declare -gx" "copy_setup_script" "0"
add_var "declare -gx" "add_soft" "0"
add_var "declare -gx" "networkmanager" "0"
add_var "declare -gx" "pulseaudio" "0"
add_var "declare -gx" "bluetooth" "0"
add_var "declare -gx" "printers" "0"
add_var "declare -gx" "arch" "amd64"
add_var "declare -gx" "debian_distr" "buster"
add_var "declare -gA" "debian_repos"
add_var "declare -gx" "debian_repos[updates]" "${debian_repos[updates]}"
add_var "declare -gx" "debian_repos[backports]" "${debian_repos[backports]}"
add_var "declare -gx" "debian_repos[main]" "${debian_repos[main]}"
add_var "declare -gx" "debian_repos[security]" "${debian_repos[security]}"
add_var "declare -gx" "repos" "0"
add_var "declare -gx" "kernel" "0"
add_var "declare -gx" "debian_add_i386" "1"
add_var "declare -gx" "preinstall" "locales"
add_var "declare -gx" "postinstall" ""
add_var "declare -gx" "LANG" "en_US.UTF-8"
