name: "Build new ISO and PXE archive"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install -y git squashfs-tools genisoimage p7zip-full wget zstd cpio
      - name: Build public edition
        run: |
          sudo env LI_TYPE=public ./bin/make_images/build.sh
      - name: Upload images to Release
        uses: ncipollo/release-action@main
        with:
          artifacts: releases/*
          body: |
            For change log, plesase see this [file](docs/CHANGES.md)
            Default user:password are root:pass
            SSH is working on port 22.
