name: "Test directory default and by-profile install"

on:
  pull_request:
    - paths:
      - 'auto_configs/**'
  push:
    - paths:
      - 'auto_configs/**'
  workflow_dispatch:

jobs:
  test_profiles:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install needed packages
        run: |
          sudo apt update
          sudo apt install -y debootstrap
      - name: Test all included profiles (except live ones)
        run: |
          sudo ./tests/profile_test.sh $(echo $(find ./auto_configs/ -not -path "./auto_configs/live/*" -name '*.sh' | sed -e 's|\n| |g'))
